/**
 * This class is generated by jOOQ
 */
package tech.codingclub.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.tables.records.MusicRecord> implements org.jooq.Record7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 753511654;

	/**
	 * Setter for <code>public.music.parent_link</code>.
	 */
	public void setParentLink(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.music.parent_link</code>.
	 */
	public java.lang.String getParentLink() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.music.link</code>.
	 */
	public void setLink(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.music.link</code>.
	 */
	public java.lang.String getLink() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.music.album</code>.
	 */
	public void setAlbum(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.music.album</code>.
	 */
	public java.lang.String getAlbum() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.music.singers</code>.
	 */
	public void setSingers(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.music.singers</code>.
	 */
	public java.lang.String getSingers() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.music.lyricist</code>.
	 */
	public void setLyricist(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.music.lyricist</code>.
	 */
	public java.lang.String getLyricist() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.music.music_director</code>.
	 */
	public void setMusicDirector(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.music.music_director</code>.
	 */
	public java.lang.String getMusicDirector() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.music.duration</code>.
	 */
	public void setDuration(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.music.duration</code>.
	 */
	public java.lang.String getDuration() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.tables.Music.MUSIC.PARENT_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.tables.Music.MUSIC.LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.tables.Music.MUSIC.ALBUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.tables.Music.MUSIC.SINGERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.tables.Music.MUSIC.LYRICIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return tech.codingclub.tables.Music.MUSIC.MUSIC_DIRECTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return tech.codingclub.tables.Music.MUSIC.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getParentLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAlbum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getSingers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLyricist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMusicDirector();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value1(java.lang.String value) {
		setParentLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value2(java.lang.String value) {
		setLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value3(java.lang.String value) {
		setAlbum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value4(java.lang.String value) {
		setSingers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value5(java.lang.String value) {
		setLyricist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value6(java.lang.String value) {
		setMusicDirector(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord value7(java.lang.String value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MusicRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MusicRecord
	 */
	public MusicRecord() {
		super(tech.codingclub.tables.Music.MUSIC);
	}

	/**
	 * Create a detached, initialised MusicRecord
	 */
	public MusicRecord(java.lang.String parentLink, java.lang.String link, java.lang.String album, java.lang.String singers, java.lang.String lyricist, java.lang.String musicDirector, java.lang.String duration) {
		super(tech.codingclub.tables.Music.MUSIC);

		setValue(0, parentLink);
		setValue(1, link);
		setValue(2, album);
		setValue(3, singers);
		setValue(4, lyricist);
		setValue(5, musicDirector);
		setValue(6, duration);
	}
}
